#spring.datasource.url: jdbc:h2:file:./camunda-h2-database
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blps
    username: postgres
    password: DenDenvv
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl_auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

camunda.bpm.admin-user:
  id: demo
  password: demo

camunda:
  bpm:
    authorization:
      enabled: true

JWT_SECRET_KEY: "XtakcfRhKkIzbFPTqG5Al5wxGMPhIUJvOMTvNPfB/g37MAxTFjpmZqxbLR0tTazU"
SUBSCRIPTION_PRICE: 300
LIST_OF_USERS: "users.xml"